//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBVideoRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Details()
        {
            this.Movie_Details = new HashSet<Movie_Details>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Password_Hash { get; set; }
        public string Security_Stamp { get; set; }
        public long Phone_Number { get; set; }
        public string Aadhar_Number { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Update_Time_Stamp { get; set; }
    
        public virtual Customer_Details Customer_Details1 { get; set; }
        public virtual Customer_Details Customer_Details2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie_Details> Movie_Details { get; set; }
    }
}
