//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JBVideoRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Details
    {
        public long Movie_Id { get; set; }
        public long Id { get; set; }
        public string Movie_Name { get; set; }
        public string Genre { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public int Movies_In_Stock { get; set; }
        public int Movies_Availablility { get; set; }
        public string Account_Number { get; set; }
        public string Video_File { get; set; }
        public bool Is_Subscribed_To_Newletter { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Create_Time_Stamp { get; set; }
        public System.DateTime Update_Time_Stamp { get; set; }
    
        public virtual Customer_Details Customer_Details { get; set; }
    }
}
